language: python
python:
  - '2.7'
  - '3.4'

install:
  - pip install --upgrade pytest coverage codecov
  - pip install .
  - python manage.py migrate

script:
  - coverage run --source mysite -m py.test

after_success:
  - codecov
